name: Create Release and Run Tests

on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Deploy to server
      run: |
        echo "Deploying to production server..."
        # Add your deployment commands here.
        # For example, you might use scp or rsync to copy files,
        # or use a tool like Ansible or Docker to deploy your application. 